version: "2"


exclude_patterns:
  "config/",
  "db/",
  "dist/",
  "features/",
  "**/node_modules/",
  "script/",
  "**/spec/",
  "**/test/",
  "**/tests/",
  "Tests/",
  "**/vendor/",
  "**/*_test.go",
  "**/*.d.ts"

plugins: 
  eslint: 
    enabled: true
    channel: "eslint-5"
